services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5042"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./AuthService:/app
    working_dir: /app

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SenhaForte@123"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"SenhaForte@123\" -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mssql_data:
